package GUI;

import com.mysql.jdbc.Statement;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.Connection;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.Timer;
import java.sql.PreparedStatement;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Alvin
 */
public class HalamanUtama extends javax.swing.JFrame {    
    Connection con;
    Statement st;
    ResultSet rs;
    String sql, ket_m, kat_m, ket_k, kat_k, tgl, bln, thn;
    DefaultTableModel model_m, model_k;
    int pemasukan, pengeluaran;
    PreparedStatement p ;
    
    
    public HalamanUtama() {
        initComponents();
        Show_tanggal();
        Show_waktu();
        setExtendedState(JFrame.MAXIMIZED_HORIZ);
        setVisible(true);
        setResizable(false);
         //Koneksi
         Koneksi DB =  new Koneksi();
        DB.getCon();
        con = DB.con;
        st = (Statement) DB.stm;  
        
        model_m = (DefaultTableModel)tb_pemasukan_h.getModel();
        tb_pemasukan_h.setModel(model_m);
        
        model_k = (DefaultTableModel)tb_pengeluaran_h.getModel();
        tb_pengeluaran_h.setModel(model_k);
        //
    load();
    load_keluar();
    
    }
    
    public void Show_tanggal()
    {
        Date d = new Date();
        SimpleDateFormat s = new SimpleDateFormat("dd-MM-yyyy");
        l_date.setText(s.format(d));
    }
    
    public void Show_waktu()
    {
        new Timer (0, new ActionListener() {
            @Override
            public void actionPerformed(ActionEvent ae) {
                Date d = new Date();
                SimpleDateFormat s = new SimpleDateFormat("hh:mm:ss");
                l_waktu.setText(s.format(d)); 
            }
        }).start();
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel2 = new javax.swing.JPanel();
        MainPanel = new javax.swing.JPanel();
        pnl_home = new javax.swing.JPanel();
        Home = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tb_pengeluaran_h = new javax.swing.JTable();
        r_pengeluaran = new javax.swing.JTextField();
        jTextField2 = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jScrollPane3 = new javax.swing.JScrollPane();
        tb_pemasukan_h = new javax.swing.JTable();
        Pengeluaran = new javax.swing.JPanel();
        btn_save_k = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        txt_ket_k = new javax.swing.JTextField();
        btn_reset_k = new javax.swing.JButton();
        txt_kat_k = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        txt_jmlh_k = new javax.swing.JTextField();
        cmb_tgl = new javax.swing.JComboBox<>();
        cmb_bln = new javax.swing.JComboBox<>();
        cmb_th = new javax.swing.JComboBox<>();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        history = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel6 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jTextField8 = new javax.swing.JTextField();
        masukan = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        txt_ket_m = new javax.swing.JTextField();
        txt_kat_m = new javax.swing.JTextField();
        txt_jmlh_m = new javax.swing.JTextField();
        btn_save_m = new javax.swing.JButton();
        btn_reset_m = new javax.swing.JButton();
        cmb_tgl_m = new javax.swing.JComboBox<>();
        cmb_bln_m = new javax.swing.JComboBox<>();
        cmb_th_m = new javax.swing.JComboBox<>();
        Menu = new javax.swing.JPanel();
        tb_masukan = new javax.swing.JButton();
        tb_pengeluaran = new javax.swing.JButton();
        tb_home = new javax.swing.JButton();
        tb_keluar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        l_date = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        l_waktu = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        MainPanel.setBackground(new java.awt.Color(0, 102, 255));

        pnl_home.setBackground(new java.awt.Color(255, 255, 255));
        pnl_home.setLayout(new java.awt.CardLayout());

        tb_pengeluaran_h.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Pemasukan", "Kategori", "pengeluaran"
            }
        ));
        jScrollPane2.setViewportView(tb_pengeluaran_h);

        jTextField2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField2ActionPerformed(evt);
            }
        });

        jLabel5.setText("Rata-Rata pengeluaraan Perhari");

        jLabel17.setText("Rata-Rata pengemasukan  Perhari");

        tb_pemasukan_h.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Tanggal", "Pengmasukan", "kategori", "keterangan"
            }
        ));
        jScrollPane3.setViewportView(tb_pemasukan_h);

        javax.swing.GroupLayout HomeLayout = new javax.swing.GroupLayout(Home);
        Home.setLayout(HomeLayout);
        HomeLayout.setHorizontalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, HomeLayout.createSequentialGroup()
                        .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(HomeLayout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel17))
                            .addGroup(HomeLayout.createSequentialGroup()
                                .addComponent(r_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 179, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 192, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(63, 63, 63))
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE))
                .addContainerGap())
        );
        HomeLayout.setVerticalGroup(
            HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(HomeLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 141, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(jLabel17))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(HomeLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(r_pengeluaran, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addGap(12, 12, 12))
        );

        pnl_home.add(Home, "card5");

        btn_save_k.setText("Save");
        btn_save_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_kActionPerformed(evt);
            }
        });

        jLabel11.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel11.setText("Keterangan ");

        btn_reset_k.setText("Reset");

        txt_kat_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kat_kActionPerformed(evt);
            }
        });

        jLabel12.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel12.setText("Kategori");

        jLabel13.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel13.setText("Jumlah");

        txt_jmlh_k.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlh_kActionPerformed(evt);
            }
        });

        cmb_tgl.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmb_bln.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "januari", "Februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember" }));

        cmb_th.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        jLabel14.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel14.setText("Tanggal");

        jLabel15.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel15.setText(" Pengeluaraan baru");

        javax.swing.GroupLayout PengeluaranLayout = new javax.swing.GroupLayout(Pengeluaran);
        Pengeluaran.setLayout(PengeluaranLayout);
        PengeluaranLayout.setHorizontalGroup(
            PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengeluaranLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel15)
                    .addGroup(PengeluaranLayout.createSequentialGroup()
                        .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12)
                            .addComponent(jLabel13)
                            .addComponent(jLabel14))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txt_ket_k)
                            .addComponent(txt_jmlh_k)
                            .addComponent(txt_kat_k)
                            .addGroup(PengeluaranLayout.createSequentialGroup()
                                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(PengeluaranLayout.createSequentialGroup()
                                        .addComponent(btn_save_k)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_reset_k))
                                    .addGroup(PengeluaranLayout.createSequentialGroup()
                                        .addComponent(cmb_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(3, 3, 3)
                                        .addComponent(cmb_bln, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(cmb_th, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(232, 232, 232))
        );
        PengeluaranLayout.setVerticalGroup(
            PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(PengeluaranLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel15)
                .addGap(21, 21, 21)
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel14)
                    .addComponent(cmb_bln, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_th, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tgl, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel13)
                    .addComponent(txt_jmlh_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel12)
                    .addComponent(txt_kat_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel11)
                    .addComponent(txt_ket_k, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(PengeluaranLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_k)
                    .addComponent(btn_reset_k))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pnl_home.add(Pengeluaran, "card3");

        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "tanggal", "jenis", "jumlah", "kategori", "Keteterangan"
            }
        ));
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
            jTable1.getColumnModel().getColumn(2).setResizable(false);
            jTable1.getColumnModel().getColumn(4).setResizable(false);
        }

        jLabel6.setText("Rata-Rata Pengeluaran");

        jLabel16.setText("Rata-Rata Pemasukan");

        javax.swing.GroupLayout historyLayout = new javax.swing.GroupLayout(history);
        history.setLayout(historyLayout);
        historyLayout.setHorizontalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 509, Short.MAX_VALUE)
                    .addGroup(historyLayout.createSequentialGroup()
                        .addGroup(historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel16)
                                .addComponent(jTextField7))
                            .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 126, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
        );
        historyLayout.setVerticalGroup(
            historyLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(historyLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 160, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel6)
                .addGap(1, 1, 1)
                .addComponent(jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jLabel16)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(57, Short.MAX_VALUE))
        );

        pnl_home.add(history, "card4");

        jLabel1.setFont(new java.awt.Font("Centaur", 1, 18)); // NOI18N
        jLabel1.setText("Pemasukan Baru");

        jLabel7.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel7.setText("Tanggal");

        jLabel8.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel8.setText("Jumlah");

        jLabel9.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel9.setText("Keterangan ");

        jLabel10.setFont(new java.awt.Font("Agency FB", 1, 14)); // NOI18N
        jLabel10.setText("Kategori");

        txt_kat_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_kat_mActionPerformed(evt);
            }
        });

        txt_jmlh_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txt_jmlh_mActionPerformed(evt);
            }
        });

        btn_save_m.setText("Save");
        btn_save_m.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_save_mActionPerformed(evt);
            }
        });

        btn_reset_m.setText("Reset");

        cmb_tgl_m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "1", "2", "3", "4", "6", "7", "8", "9", "10", "11", "12", "13", "14", "15", "16", "17", "18", "19", "20", "21", "22", "23", "24", "25", "26", "27", "28", "29", "30", "31" }));

        cmb_bln_m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "januari", "Februari", "maret", "april", "mei", "juni", "juli", "agustus", "september", "oktober", "november", "desember" }));

        cmb_th_m.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "2017", "2018", "2019", "2020", "2021", "2022", "2023", "2024", "2025", "2026", "2027", "2028" }));

        javax.swing.GroupLayout masukanLayout = new javax.swing.GroupLayout(masukan);
        masukan.setLayout(masukanLayout);
        masukanLayout.setHorizontalGroup(
            masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukanLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addGroup(masukanLayout.createSequentialGroup()
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(jLabel7))
                        .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(masukanLayout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txt_ket_m)
                                    .addComponent(txt_jmlh_m)
                                    .addComponent(txt_kat_m)
                                    .addGroup(masukanLayout.createSequentialGroup()
                                        .addComponent(btn_save_m)
                                        .addGap(18, 18, 18)
                                        .addComponent(btn_reset_m)
                                        .addGap(0, 0, Short.MAX_VALUE))))
                            .addGroup(masukanLayout.createSequentialGroup()
                                .addGap(11, 11, 11)
                                .addComponent(cmb_tgl_m, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_bln_m, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmb_th_m, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addGap(227, 227, 227))
        );
        masukanLayout.setVerticalGroup(
            masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(masukanLayout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1)
                .addGap(21, 21, 21)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(cmb_bln_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_th_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(cmb_tgl_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel8)
                    .addComponent(txt_jmlh_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel10)
                    .addComponent(txt_kat_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel9)
                    .addComponent(txt_ket_m, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(masukanLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_save_m)
                    .addComponent(btn_reset_m))
                .addContainerGap(80, Short.MAX_VALUE))
        );

        pnl_home.add(masukan, "card2");

        Menu.setBackground(new java.awt.Color(51, 51, 255));

        tb_masukan.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-plus-48.png"))); // NOI18N
        tb_masukan.setText("masukan");
        tb_masukan.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_masukanActionPerformed(evt);
            }
        });

        tb_pengeluaran.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-plus-48 (1).png"))); // NOI18N
        tb_pengeluaran.setText("pengeluaran");
        tb_pengeluaran.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_pengeluaranActionPerformed(evt);
            }
        });

        tb_home.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-home-48.png"))); // NOI18N
        tb_home.setText("Home");
        tb_home.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_homeActionPerformed(evt);
            }
        });

        tb_keluar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-exit-48.png"))); // NOI18N
        tb_keluar.setText("Keluar");
        tb_keluar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tb_keluarActionPerformed(evt);
            }
        });

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/1486564168-finance-bank-check_81495.png"))); // NOI18N

        javax.swing.GroupLayout MenuLayout = new javax.swing.GroupLayout(Menu);
        Menu.setLayout(MenuLayout);
        MenuLayout.setHorizontalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addGroup(MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tb_pengeluaran, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tb_masukan, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tb_home, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, MenuLayout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addComponent(jLabel3)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addGroup(MenuLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(tb_keluar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
        );
        MenuLayout.setVerticalGroup(
            MenuLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MenuLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(tb_home)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_masukan)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_pengeluaran)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(tb_keluar)
                .addGap(154, 154, 154))
        );

        jLabel2.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-calendar-48.png"))); // NOI18N

        l_date.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        l_date.setForeground(new java.awt.Color(255, 255, 255));
        l_date.setText("jLabel3");

        jLabel4.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/gambar/icons8-clock-48.png"))); // NOI18N

        l_waktu.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N
        l_waktu.setForeground(new java.awt.Color(255, 255, 255));
        l_waktu.setText("jLabel5");

        javax.swing.GroupLayout MainPanelLayout = new javax.swing.GroupLayout(MainPanel);
        MainPanel.setLayout(MainPanelLayout);
        MainPanelLayout.setHorizontalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(MainPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 521, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_date))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(l_waktu, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        MainPanelLayout.setVerticalGroup(
            MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(12, 12, 12)
                        .addComponent(jLabel4))
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addComponent(l_waktu)))
                .addGroup(MainPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(jLabel2)
                        .addGap(18, 18, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, MainPanelLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(l_date)
                        .addGap(30, 30, 30)))
                .addComponent(pnl_home, javax.swing.GroupLayout.PREFERRED_SIZE, 348, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
            .addComponent(Menu, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(MainPanel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void tb_masukanActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_masukanActionPerformed
       pnl_home.removeAll();
       pnl_home.repaint();
       pnl_home.validate();
       
       pnl_home.add(masukan);
       pnl_home.repaint();
       pnl_home.revalidate();
    }//GEN-LAST:event_tb_masukanActionPerformed

    private void tb_pengeluaranActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_pengeluaranActionPerformed
        // TODO add your handling code here:
       pnl_home.removeAll();
       pnl_home.repaint();
       pnl_home.validate();
       
       pnl_home.add(Pengeluaran);
       pnl_home.repaint();
       pnl_home.revalidate();
    }//GEN-LAST:event_tb_pengeluaranActionPerformed

    private void tb_homeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_homeActionPerformed
        // TODO add your handling code here:
         pnl_home.removeAll();
       pnl_home.repaint();
       pnl_home.validate();
       
       pnl_home.add(Home);
       pnl_home.repaint();
       pnl_home.revalidate();
    }//GEN-LAST:event_tb_homeActionPerformed

    private void txt_jmlh_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlh_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlh_mActionPerformed

    private void txt_kat_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kat_mActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kat_mActionPerformed

    private void tb_keluarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tb_keluarActionPerformed
       int dialogBtn = JOptionPane.YES_NO_OPTION;
       int dialogResult = JOptionPane.showConfirmDialog(this,"Anda Yakin keluar ?", "Peringatan", dialogBtn);
        if (dialogResult == 0) {
            System.exit(0);
        } else {
        }
    }//GEN-LAST:event_tb_keluarActionPerformed

    private void txt_jmlh_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_jmlh_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_jmlh_kActionPerformed

    private void txt_kat_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txt_kat_kActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txt_kat_kActionPerformed

    private void btn_save_kActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_kActionPerformed
       pengeluaran = Integer.parseInt(txt_jmlh_k.getText());
       kat_k = txt_kat_k.getText();
       ket_k = txt_ket_k.getText();
       tgl = cmb_tgl.getSelectedItem().toString();
       bln = cmb_bln.getSelectedItem().toString(); 
       thn  = cmb_th.getSelectedItem().toString();
       String tanggal = thn+"-"+bln+"-"+tgl;
    
       try {    
           sql = "INSERT INTO pengeluaran(`Tanggal`,`pengeluaran`,`keterangan`,`kategori`) "
                   + "VALUES(?,?,?,?)";
           p = con.prepareStatement(sql);
           p.setString(1,tanggal);
           p.setInt(2, pengeluaran);
           p.setString(3,ket_k);
           p.setString(4,kat_k);
            p.executeUpdate();
            p.close(); 
             JOptionPane.showMessageDialog(null, "Sukses" );
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "gagal "+e);
        }       
    }//GEN-LAST:event_btn_save_kActionPerformed

    private void btn_save_mActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_save_mActionPerformed
      
       pemasukan = Integer.parseInt(txt_jmlh_m.getText());
       kat_m = txt_kat_m.getText();
       ket_m = txt_ket_m.getText();
       tgl = cmb_tgl_m.getSelectedItem().toString();
       bln = cmb_bln_m.getSelectedItem().toString(); 
       thn  = cmb_th_m.getSelectedItem().toString();
       String tanggal = thn+"-"+bln+"-"+tgl;
    
       try {    
           sql = "INSERT INTO pemasukan(`Tgl`,`pemasukan`,`keterangan`,`kategori`) "
                   + "VALUES(?,?,?,?)";
           p = con.prepareStatement(sql);
           p.setString(1,tanggal);
           p.setInt(2, pemasukan);
           p.setString(3,ket_m);
           p.setString(4,kat_m);
            p.executeUpdate();
            p.close(); 
             JOptionPane.showMessageDialog(null, "Sukses" );
            
        } catch(SQLException e){
            JOptionPane.showMessageDialog(null, "gagal "+e);
        }
       
    }//GEN-LAST:event_btn_save_mActionPerformed

    private void jTextField2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField2ActionPerformed

    void load()
    {
        try {
            
            sql = "SELECT * FROM pemasukan";
            rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                Object [] obj = new Object[4];
                obj [0] = rs.getString("tgl");
                obj [1] = rs.getInt("pemasukan");
                obj [2] = rs.getString("kategori");
                obj [3] = rs.getString("keterangan");
                model_m.addRow(obj);
            }
        
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal" + e);
        }
    }
    void load_keluar()
    {
        try {
            
            sql = "SELECT * FROM pengeluaran";
            rs = st.executeQuery(sql);
            
            while(rs.next())
            {
                Object [] obj = new Object[4];
                obj [0] = rs.getString("tanggal");
                obj [1] = rs.getInt("keluar");
                obj [2] = rs.getString("kategori");
                obj [3] = rs.getString("keterangan");
                model_k.addRow(obj);
            }
          
        } catch (SQLException e) {
            JOptionPane.showMessageDialog(null, "gagal" + e);
        }
    }
   
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Home;
    private javax.swing.JPanel MainPanel;
    private javax.swing.JPanel Menu;
    private javax.swing.JPanel Pengeluaran;
    private javax.swing.JButton btn_reset_k;
    private javax.swing.JButton btn_reset_m;
    private javax.swing.JButton btn_save_k;
    private javax.swing.JButton btn_save_m;
    private javax.swing.JComboBox<String> cmb_bln;
    private javax.swing.JComboBox<String> cmb_bln_m;
    private javax.swing.JComboBox<String> cmb_tgl;
    private javax.swing.JComboBox<String> cmb_tgl_m;
    private javax.swing.JComboBox<String> cmb_th;
    private javax.swing.JComboBox<String> cmb_th_m;
    private javax.swing.JPanel history;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JTable jTable1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField jTextField8;
    private javax.swing.JLabel l_date;
    private javax.swing.JLabel l_waktu;
    private javax.swing.JPanel masukan;
    private javax.swing.JPanel pnl_home;
    private javax.swing.JTextField r_pengeluaran;
    private javax.swing.JButton tb_home;
    private javax.swing.JButton tb_keluar;
    private javax.swing.JButton tb_masukan;
    private javax.swing.JTable tb_pemasukan_h;
    private javax.swing.JButton tb_pengeluaran;
    private javax.swing.JTable tb_pengeluaran_h;
    private javax.swing.JTextField txt_jmlh_k;
    private javax.swing.JTextField txt_jmlh_m;
    private javax.swing.JTextField txt_kat_k;
    private javax.swing.JTextField txt_kat_m;
    private javax.swing.JTextField txt_ket_k;
    private javax.swing.JTextField txt_ket_m;
    // End of variables declaration//GEN-END:variables
}
